nodeLinker: pnp
pnpMode: loose
enableGlobalCache: true

supportedArchitectures:
  os: [darwin, linux, win32]
  cpu: [x64, arm64]

packageExtensions:
  "@prisma/client@*":
    dependencies:
      "@prisma/engines-version": "*"
  "@testing-library/react@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "vite@*":
    peerDependencies:
      "@types/node": "*"
    dependencies:
      "supports-color": "*"
      "ts-node": "*"

yarnPath: .yarn/releases/yarn-4.5.3.cjs